"use client";
import { useMemo, useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
import { deleteImportClassificationRule, saveImportClassificationRule, type ImportRuleAction } from "@/lib/actions/import-classification-rule-actions";

type Item={id:string;name:string;institutionName:string|null};
type Rule={id:string;matchText:string;action:ImportRuleAction;targetType:"ACCOUNT"|"INVESTMENT";targetId:string;targetName:string|null};
type Draft={id?:string;matchText:string;action:ImportRuleAction;targetType:"ACCOUNT"|"INVESTMENT";targetId:string};
const suggestions:Draft[]=[{matchText:"RESGATE POUPANCA",action:"TRANSFER_IN",targetType:"ACCOUNT",targetId:""},{matchText:"OUROCAP",action:"INVESTMENT_CONTRIBUTION",targetType:"INVESTMENT",targetId:""},{matchText:"RF LP HIGH",action:"INVESTMENT_CONTRIBUTION",targetType:"INVESTMENT",targetId:""}];
const actionLabels:Record<ImportRuleAction,string>={TRANSFER_IN:"Transferência entre contas — entrada",TRANSFER_OUT:"Transferência entre contas — saída",INVESTMENT_CONTRIBUTION:"Aplicação em investimento",INVESTMENT_WITHDRAWAL:"Resgate de investimento"};
function flow(r:{action:ImportRuleAction;targetName:string|null}){const target=r.targetName||"alvo não encontrado"; if(r.action==="INVESTMENT_CONTRIBUTION")return <>Debita <b>(sai)</b> da conta do extrato → Credita <b>(entra)</b> no investimento <b>{target}</b></>; if(r.action==="INVESTMENT_WITHDRAWAL")return <>Debita <b>(sai)</b> do investimento <b>{target}</b> → Credita <b>(entra)</b> na conta do extrato</>; if(r.action==="TRANSFER_OUT")return <>Debita <b>(sai)</b> da conta do extrato → Credita <b>(entra)</b> na conta <b>{target}</b></>; return <>Debita <b>(sai)</b> da conta <b>{target}</b> → Credita <b>(entra)</b> na conta do extrato</>;}
export function ImportRulesClient({accounts,investments,rules}:{accounts:Item[];investments:Item[];rules:Rule[]}){const[editor,setEditor]=useState<Draft|null>(null);const[saving,setSaving]=useState(false);const missing=useMemo(()=>suggestions.filter(s=>!rules.some(r=>r.matchText.toUpperCase()===s.matchText)),[rules]);const change=(p:Partial<Draft>)=>setEditor(v=>v?{...v,...p}:v);const save=async()=>{if(!editor?.matchText||!editor.targetId)return;setSaving(true);try{await saveImportClassificationRule(editor);setEditor(null)}finally{setSaving(false)}};const list=editor?.targetType==="INVESTMENT"?investments:accounts;return <section className="glass-card max-w-5xl rounded-2xl p-6 space-y-4"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold text-white">Motor de regras de importação</h2><p className="mt-1 text-xs text-muted-foreground">Cada regra descreve claramente o dinheiro que sai e o dinheiro que entra.</p></div><button onClick={()=>setEditor({matchText:"",action:"INVESTMENT_CONTRIBUTION",targetType:"INVESTMENT",targetId:""})} className="inline-flex items-center gap-1 rounded-lg bg-cyan-500/15 px-3 py-2 text-xs font-bold text-cyan-200"><Plus className="h-4 w-4"/>Nova regra</button></div>
{editor&&<div className="rounded-2xl border border-cyan-400/30 bg-cyan-500/[.06] p-4 space-y-3"><div className="flex justify-between"><b className="text-sm text-white">{editor.id?"Editar regra":"Nova regra"}</b><button onClick={()=>setEditor(null)}><X className="h-4 w-4 text-slate-300"/></button></div><div className="grid gap-2 md:grid-cols-3"><input value={editor.matchText} onChange={e=>change({matchText:e.target.value})} placeholder="Texto que vem no OFX" className="rounded-lg bg-slate-900 p-2 text-xs text-white"/><select value={editor.action} onChange={e=>{const action=e.target.value as ImportRuleAction;change({action,targetType:action.startsWith("INVESTMENT")?"INVESTMENT":"ACCOUNT",targetId:""})}} className="rounded-lg bg-slate-900 p-2 text-xs text-white">{Object.entries(actionLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select value={editor.targetId} onChange={e=>change({targetId:e.target.value})} className="rounded-lg bg-slate-900 p-2 text-xs text-white"><option value="">Selecionar {editor.targetType==="INVESTMENT"?"investimento":"conta"}...</option>{list.map(x=><option key={x.id} value={x.id}>{x.institutionName?x.institutionName+" · ":""}{x.name}</option>)}</select></div><button disabled={!editor.matchText||!editor.targetId||saving} onClick={save} className="rounded-lg bg-emerald-500 px-3 py-2 text-xs font-bold text-slate-950 disabled:opacity-40">{saving?"Salvando":"Salvar regra"}</button></div>}
{rules.length>0&&<div className="space-y-2">{rules.map(r=><div key={r.id} className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-3"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold text-cyan-200">Quando o extrato contiver “{r.matchText}”</p><p className="mt-1 text-sm text-white">{flow(r)}</p></div><div className="flex gap-2"><button onClick={()=>setEditor({id:r.id,matchText:r.matchText,action:r.action,targetType:r.targetType,targetId:r.targetId})} className="rounded-lg p-2 text-cyan-300"><Pencil className="h-4 w-4"/></button><button onClick={()=>deleteImportClassificationRule(r.id)} className="rounded-lg p-2 text-rose-300"><Trash2 className="h-4 w-4"/></button></div></div></div>)}</div>}
{missing.length>0&&!editor&&<div className="border-t border-white/10 pt-4"><p className="mb-2 text-xs text-muted-foreground">Sugestões ainda não configuradas</p><div className="flex flex-wrap gap-2">{missing.map(s=><button key={s.matchText} onClick={()=>setEditor(s)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-200 hover:bg-white/5">+ {s.matchText}</button>)}</div></div>}</section>}
