"use client";

import { useMemo, useState } from "react";
import { ArrowDownRight, ArrowRightLeft, ArrowUpRight, Layers, Pencil, Search, Shuffle, Trash2, X } from "lucide-react";
import { updateSimpleTransaction, deleteSimpleTransaction } from "@/lib/actions/transaction-management-actions";

export interface TransactionRow {
  id: string; description: string; amount: number; date: string; direction: string; transactionType: string;
  accountName: string; destinationAccountName?: string | null; categoryId?: string | null; categoryName?: string | null;
  notes?: string | null; allocations: { id: string; allocationType: string; amount: number; label: string }[];
}
export interface CategoryOption { id: string; name: string; parentName?: string | null; }
const editable = new Set(["INCOME", "EXPENSE", "REFUND", "INTEREST_INCOME", "INTEREST_EXPENSE", "FEE", "OTHER"]);
const money = (v:number) => new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
const labels:Record<string,string>={INCOME:"Receita",EXPENSE:"Despesa",TRANSFER:"Transferência",ASSET_PURCHASE:"Compra de bem",LIABILITY_PAYMENT:"Pagamento de dívida",LOAN_RECEIVED:"Empréstimo recebido",REFUND:"Reembolso",INTEREST_INCOME:"Juros recebidos",INTEREST_EXPENSE:"Juros",FEE:"Tarifa",OTHER:"Outro"};

export function TransactionsClient({ initialTransactions, categories }: { initialTransactions: TransactionRow[]; categories: CategoryOption[] }) {
  const [items,setItems]=useState(initialTransactions), [query,setQuery]=useState(""), [editing,setEditing]=useState<TransactionRow|null>(null), [busy,setBusy]=useState(false), [error,setError]=useState<string|null>(null);
  const filtered=useMemo(()=>items.filter(x=>[x.description,x.accountName,x.categoryName].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase())),[items,query]);
  const save=async(form:FormData)=>{ if(!editing)return; setBusy(true);setError(null);try{await updateSimpleTransaction({id:editing.id,description:String(form.get("description")),amount:Number(form.get("amount")),date:String(form.get("date")),categoryId:String(form.get("categoryId"))||null,notes:String(form.get("notes"))||null});window.location.reload()}catch(e:any){setError(e.message||"Não foi possível salvar.")}finally{setBusy(false)}};
  const remove=async(tx:TransactionRow)=>{if(!confirm(`Excluir “${tx.description}”? O saldo da conta será revertido.`))return;setBusy(true);try{await deleteSimpleTransaction(tx.id);setItems(v=>v.filter(x=>x.id!==tx.id))}catch(e:any){alert(e.message||"Não foi possível excluir.")}finally{setBusy(false)}};
  return <div className="space-y-5">
    <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><h1 className="text-2xl font-bold text-white">Transações & Operações</h1><p className="text-xs text-muted-foreground">Edite lançamentos simples; operações patrimoniais exigem estorno próprio.</p></div><label className="flex items-center gap-2 rounded-xl bg-white/5 border border-white/10 px-3 py-2 text-xs"><Search className="w-4 h-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar transação" className="bg-transparent outline-none text-white w-52"/></label></div>
    {filtered.map(tx=>{const credit=tx.direction==="CREDIT", transfer=tx.transactionType==="TRANSFER", canEdit=editable.has(tx.transactionType)&&tx.allocations.length<=1;return <div key={tx.id} className="glass-card p-4 rounded-2xl space-y-3"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className={"w-10 h-10 rounded-xl flex items-center justify-center "+(transfer?"bg-purple-500/20 text-purple-400":credit?"bg-emerald-500/20 text-emerald-400":"bg-rose-500/20 text-rose-400")}>{transfer?<Shuffle className="w-5 h-5"/>:credit?<ArrowDownRight className="w-5 h-5"/>:<ArrowUpRight className="w-5 h-5"/>}</div><div><h3 className="font-bold text-white text-sm">{tx.description}</h3><p className="text-xs text-muted-foreground">{tx.accountName}{tx.destinationAccountName?` → ${tx.destinationAccountName}`:""} · {new Date(tx.date).toLocaleDateString("pt-BR")}{tx.categoryName?` · ${tx.categoryName}`:""}</p></div></div><div className="text-right"><strong className={credit?"text-emerald-400":"text-white"}>{credit?"+":"-"}{money(tx.amount)}</strong><p className="text-[11px] text-muted-foreground">{labels[tx.transactionType]||tx.transactionType}</p></div></div>
    {tx.allocations.length>1&&<div className="rounded-xl bg-black/20 p-3 text-xs text-slate-300"><div className="text-cyan-400 font-semibold mb-1 flex gap-1"><Layers className="w-3.5 h-3.5"/>Rateio</div>{tx.allocations.map(a=><div key={a.id} className="flex justify-between"><span>{a.label}</span><span>{money(a.amount)}</span></div>)}</div>}
    <div className="flex justify-end gap-2 border-t border-white/5 pt-2">{canEdit?<><button disabled={busy} onClick={()=>{setEditing(tx);setError(null)}} className="px-3 py-1.5 text-xs rounded-lg bg-cyan-500/10 text-cyan-300"><Pencil className="w-3.5 h-3.5 inline mr-1"/>Editar</button><button disabled={busy} onClick={()=>remove(tx)} className="px-3 py-1.5 text-xs rounded-lg bg-rose-500/10 text-rose-300"><Trash2 className="w-3.5 h-3.5 inline mr-1"/>Excluir</button></>:<span className="text-[11px] text-muted-foreground">Operação vinculada — edição segura em breve</span>}</div></div>})}
    {filtered.length===0&&<div className="glass-card rounded-2xl p-10 text-center text-sm text-muted-foreground"><ArrowRightLeft className="w-10 h-10 mx-auto mb-3"/>Nenhuma transação encontrada.</div>}
    {editing&&<div className="fixed inset-0 z-50 p-4 flex items-center justify-center bg-black/70"><form action={save} className="w-full max-w-md bg-slate-900 border border-white/10 rounded-3xl p-6 space-y-4"><div className="flex justify-between"><h2 className="font-bold text-white">Editar lançamento</h2><button type="button" onClick={()=>setEditing(null)}><X className="text-slate-400"/></button></div>{error&&<p className="text-xs text-rose-300">{error}</p>}<input name="description" defaultValue={editing.description} className="w-full p-3 rounded-xl bg-white/5 border border-white/10 text-white" placeholder="Descrição"/><input name="amount" type="number" min="0.01" step="0.01" defaultValue={editing.amount} className="w-full p-3 rounded-xl bg-white/5 border border-white/10 text-white"/><input name="date" type="date" defaultValue={editing.date.slice(0,10)} className="w-full p-3 rounded-xl bg-white/5 border border-white/10 text-white"/><select name="categoryId" defaultValue={editing.categoryId||""} className="w-full p-3 rounded-xl bg-slate-800 border border-white/10 text-white"><option value="">Sem categoria</option>{categories.map(c=><option key={c.id} value={c.id}>{c.parentName?`${c.parentName} › `:""}{c.name}</option>)}</select><textarea name="notes" defaultValue={editing.notes||""} className="w-full p-3 rounded-xl bg-white/5 border border-white/10 text-white" placeholder="Observação (opcional)"/><button disabled={busy} className="w-full py-3 rounded-xl bg-emerald-500 text-white font-bold text-sm">{busy?"Salvando...":"Salvar alterações"}</button></form></div>}
  </div>
}